[package]
name = "cita_trie"
version = "0.3.1"
authors = ["yejiayu <yejiayu.fe@gmail.com>"]
description = "Modified Patricia Tree (aka Trie)."
license = "Apache-2.0"
edition = "2018"

[dependencies]
failure = "0.1.5"
bytes = "0.4.11"
sha3 = "0.8.0"
rlp = "0.3.0"
tiny-keccak = "1.4.2"
parking_lot = "0.8"

[dev-dependencies]
rand = "0.6.3"
hex = "0.3.2"
criterion = "0.2.10"
ethereum-types = "0.5.2"

[[bench]]
name = "insert_benchmark"
harness = false
